### PR TITLE
Update given refactoring of MultivariateBases

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by schillic** [comment]
Do you mind making a new release to propagate DynamicPolynomials v0.6 to downstream packages?

**Comment by blegat** [comment]
@schillic done as PolyJuMP v0.7.5

**Comment by schillic** [comment]
Thanks, but it is only a "local" release. I meant on `General`, so that the package manger can find it.

**Comment by schillic** [comment]
Wait, it was released... but I cannot install it. Maybe I have to wait a bit...

**Comment by blegat** [comment]
Yes, the master branch needs changes of StarAlgebras that are not released yet and the next release of PolyJuMP will be breaking so I backported it. The release should be available now, isn't it ?

**Pull request merged**
