### PR TITLE
remove reference to SOSPoly in error message

### PR DESCRIPTION
**Pull request by chriscoey**
SOSPoly lives in SumOfSquares.jl and is an approximation of >= 0, so the comment is unnecessary/confusing

### CODE REVIEW

**Comment by blegat** [comment]
If the user write `@constraint(model, p >= 0, Poly(X))` we can guess that he is trying to create a nonnegative polynomial variable. He is probably using SumOfSquares and once he figures out he needs to use SOSPoly he will probably not guess that the meaning of `X` changes. It seems to me that this error message is helping the user. Of course it is not the case if he is not using SumOfSquares but at the moment as far as I know there is no other way to create a nonnegative polynomial with PolyJuMP so he should probably look into SumOfSquares. Once there are other extensions we can adapt the message

**Comment by chriscoey** [comment]
The user is already [warned here](https://github.com/JuliaOpt/PolyJuMP.jl/blob/4eb35854a163000017d6f34a45cec02f19b3e8eb/src/default.jl#L20) if they are not using SumOfSquares.

This message breaks the abstraction of PolyJuMP being about modeling with nonnegative polynomials (and SumOfSquares being responsible for approximating the true >= 0 polynomial nonnegativity constraint using SOS techniques). Hence I believe it is actually confusing. Why don't we suggest here that the user use `NonNegPoly(X)` (instead of `SOSPoly(X)`)?

**Comment by blegat** [comment]
`NonNegPoly` is for constraints as it does not have any field to store a monomial vector. We could have an equivalent for nonnegative polynomial vectors then if the user use it then he would see the error you mention if he didn't set any polymodule. That would work

**Comment by chriscoey** [comment]
Perfect

**Comment by chriscoey** [comment]
see #30

**Pull request closed without merging**
