### PR TITLE
up version

### PR DESCRIPTION
**Pull request by matbesancon**
Ups things to MOI 0.10 and JuMP 0.22

### CODE REVIEW

**Comment by matbesancon** [comment]
We are still blocked by MutableArithmetics on Multivariatebases:
```
(PolyJuMP) pkg> up
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: Unsatisfiable requirements detected for package MutableArithmetics [d8a4904e]:
 MutableArithmetics [d8a4904e] log:
 ├─possible versions are: 0.1.0-0.3.0 or uninstalled
 ├─restricted by compatibility requirements with MathOptInterface [b8f27783] to versions: 0.2.0-0.3.0
 │ └─MathOptInterface [b8f27783] log:
 │   ├─possible versions are: 0.5.0-0.10.5 or uninstalled
 │   ├─restricted to versions 0.10 by PolyJuMP [ddf597a6], leaving only versions 0.10.0-0.10.5
 │   │ └─PolyJuMP [ddf597a6] log:
 │   │   ├─possible versions are: 0.4.3 or uninstalled
 │   │   └─PolyJuMP [ddf597a6] is fixed to version 0.4.3
 │   └─restricted by compatibility requirements with JuMP [4076af6c] to versions: 0.10.4-0.10.5
 │     └─JuMP [4076af6c] log:
 │       ├─possible versions are: 0.18.3-0.22.0 or uninstalled
 │       └─restricted to versions 0.22 by PolyJuMP [ddf597a6], leaving only versions 0.22.0
 │         └─PolyJuMP [ddf597a6] log: see above
 ├─restricted by compatibility requirements with MultivariateBases [be282fd4] to versions: 0.2.1-0.2.22
 │ └─MultivariateBases [be282fd4] log:
 │   ├─possible versions are: 0.1.0-0.1.3 or uninstalled
 │   └─restricted to versions 0.1.2-0.1 by PolyJuMP [ddf597a6], leaving only versions 0.1.2-0.1.3
 │     └─PolyJuMP [ddf597a6] log: see above
 └─restricted by compatibility requirements with JuMP [4076af6c] to versions: 0.3.0 — no versions left
   └─JuMP [4076af6c] log: see above
```

**Comment by matbesancon** [comment]
ping @blegat

**Comment by blegat** [comment]
I'm updating SemialgebraicSets to MultivariatePolynomials v0.4

**Comment by blegat** [comment]
Thanks!

**Pull request merged**
